---
    extends:
        - eslint:recommended
    env:
        node: true
        es6: true
    rules:
        no-undef: warn
        no-console: off
    globals:
        Memory: false
        Game: false
