---
    extends:
        - eslint:recommended
    env:
        node: true
        es6: true
    rules:
        no-undef: warn
        no-console: off
        semi: error
        no-extra-semi: error
        no-extra-parens: error
        valid-jsdoc:
            - warn
            - requireReturn: false
        curly: error
        indent:
            - error
            - 4
            - SwitchCase: 1
        no-cond-assign:
            - error
            - always
    globals:
        Memory: false
        Game: false
        RESOURCE_ENERGY: false
        FIND_MY_CONSTRUCTION_SITES: false
        FIND_MY_STRUCTURES: false
        FIND_STRUCTURES: false
        FIND_FLAGS: false
        FIND_SOURCES: false
        FIND_DROPPED_ENERGY: false
        FIND_HOSTILE_CREEPS: false
        STRUCTURE_WALL: false
        STRUCTURE_RAMPART: false
        STRUCTURE_ROAD: false
        STRUCTURE_TOWER: false
        STRUCTURE_EXTENSION: false
        STRUCTURE_SPAWN: false
        STRUCTURE_CONTAINER: false
        ERR_NOT_IN_RANGE: false
        ERR_NOT_ENOUGH_RESOURCES: false
        OK: false
        WORK: false
        CARRY: false
        MOVE: false
        CLAIM: false
        TOUGH: false
        StructureTower: false
        StructureSpawn: false
        Creep: false
        Room: false
        Source: false
        StructureContainer: false
        Resource: false
